### ISSUE TITLE
Automatic updating of characters fails with unicode names

### ISSUE THREAD

**Issue by Crote** [vishnevskiy/battlenet#15]
As stated in the title, updating a character by referring to unknown data fails for names which require unicode characters

Code example:

```
import battlenet
REGION = battlenet.UNITED_STATES
REALM = 'Nazjatar'
GUILD = 'Excellence'

from battlenet import Connection
from battlenet import Guild
from battlenet import Character
Connection.setup()

def test_1():
    g = Guild(REGION, REALM, GUILD, fields=[Guild.MEMBERS])
    c = g.get_leader()
    foo = c.talents    # Produces an error

def test_2():
    c = Character(REGION, REALM, u'Clí')
    foo = c.talents    # Another error

def test_3():
    c = Character(REGION, REALM, u'Clí', fields=[Character.TALENTS])
    foo = c.talents    # Works fine
```

The error returned:

```
 Traceback (most recent call last):
  File "<<Work Directory>>\testsuite.py", line 17, in <module>
    foo = c.talents
  File "<<Work Directory>>\battlenet\things.py", line 254, in talents
    if self._refresh_if_not_present(Character.TALENTS):
  File "<<Work Directory>>\battlenet\things.py", line 43, in _refresh_if_not_present
    self.refresh(field)
  File "<<Work Directory>>\battlenet\things.py", line 271, in refresh
    self.name, raw=True, fields=self._fields))
  File "<<Work Directory>>\battlenet\connection.py", line 114, in get_character
    name = quote(name.lower())
  File "<<Work Directory>>\battlenet\utils.py", line 13, in quote
    return urllib.quote(normalize(name))
  File "<<Work Directory>>\battlenet\utils.py", line 7, in normalize
    name = name.decode('utf8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 2-3: unexpected end of data
```

**Comment by Crote** [comment]
Fixed & created a pull request
https://github.com/vishnevskiy/battlenet/pull/16
